<?php
declare(strict_types=1); namespace App\Services; use CodeIgniter\Database\BaseConnection; use RuntimeException;
final class SupplierCostHistoryService{public function __construct(private ?BaseConnection$db=null){$this->db??=db_connect();}
 public function snapshotProposal(int$proposalId,string$status,int$userId):int{if(!in_array($status,['sent','accepted','declined'],true))return 0;$proposal=$this->db->table('proposals')->where(['id'=>$proposalId,'deleted'=>0])->get(1)->getRow();if(!$proposal)throw new RuntimeException('La cotización no existe.');$rows=$this->db->table('proposal_items')->where(['proposal_id'=>$proposalId,'deleted'=>0])->where('item_id >',0)->where('supplier_id IS NOT NULL',null,false)->where('cost IS NOT NULL',null,false)->where('cost >',0)->get()->getResult();$count=0;$now=get_current_utc_time();foreach($rows as$r){$supplier=$this->db->table('suppliers')->where(['id'=>$r->supplier_id,'deleted'=>0])->get(1)->getRow();if(!$supplier)continue;$economic=hash('sha256',implode('|',[(int)$r->item_id,(int)$r->supplier_id,self::d($r->cost),self::d($r->rate),self::d($r->quantity),'MXN']));if($this->db->table('product_supplier_cost_history')->where(['proposal_item_id'=>$r->id,'economic_hash'=>$economic])->countAllResults())continue;$version=(int)($this->db->table('product_supplier_cost_history')->selectMax('snapshot_version','v')->where('proposal_item_id',$r->id)->get()->getRow()->v??0)+1;$this->db->table('product_supplier_cost_history')->insert(['product_id'=>$r->item_id,'supplier_id'=>$r->supplier_id,'proposal_id'=>$proposalId,'proposal_item_id'=>$r->id,'client_id'=>$proposal->client_id,'unit_cost'=>self::d($r->cost),'sale_unit_price'=>self::d($r->rate),'quantity'=>self::d($r->quantity),'currency'=>'MXN','quoted_at'=>$now,'recorded_by'=>$userId?:null,'created_at'=>$now,'source_status'=>$status,'snapshot_version'=>$version,'economic_hash'=>$economic]);$count++;}return$count;}
 public function productSummary(int$productId):array{$rows=$this->db->query('SELECT h.supplier_id,s.name supplier_name,COUNT(*) quote_count,MIN(h.unit_cost) best_cost,MAX(h.quoted_at) last_date,SUBSTRING_INDEX(GROUP_CONCAT(h.unit_cost ORDER BY h.quoted_at DESC,h.id DESC),\',\',1) last_cost FROM '.$this->db->prefixTable('product_supplier_cost_history').' h JOIN '.$this->db->prefixTable('suppliers').' s ON s.id=h.supplier_id WHERE h.product_id=? GROUP BY h.supplier_id,s.name ORDER BY last_date DESC',[$productId])->getResult();return$rows;}
 public function productIndicators(int$productId):array{$row=$this->db->query('SELECT COUNT(DISTINCT supplier_id) supplier_count,MIN(unit_cost) best_cost,MAX(quoted_at) last_date FROM '.$this->db->prefixTable('product_supplier_cost_history').' WHERE product_id=?',[$productId])->getRow();$last=$this->db->table('product_supplier_cost_history h')->select('h.unit_cost,h.quoted_at,s.name supplier_name')->join('suppliers s','s.id=h.supplier_id')->where('h.product_id',$productId)->orderBy('h.quoted_at','DESC')->orderBy('h.id','DESC')->get(1)->getRow();return['supplier_count'=>(int)($row->supplier_count??0),'best_cost'=>$row->best_cost??null,'last_cost'=>$last->unit_cost??null,'last_supplier'=>$last->supplier_name??null,'last_date'=>$last->quoted_at??null];}
 public function productHistory(int$productId):array{return$this->db->table('product_supplier_cost_history h')->select('h.*,s.name supplier_name,p.public_key,c.company_name')->join('suppliers s','s.id=h.supplier_id')->join('proposals p','p.id=h.proposal_id')->join('clients c','c.id=h.client_id')->where('h.product_id',$productId)->orderBy('h.quoted_at','DESC')->orderBy('h.id','DESC')->get()->getResult();}
 public function supplierProducts(int$supplierId):array{return$this->db->query('SELECT h.product_id,i.title,COUNT(*) quote_count,MAX(h.quoted_at) last_date,SUBSTRING_INDEX(GROUP_CONCAT(h.unit_cost ORDER BY h.quoted_at DESC,h.id DESC),\',\',1) last_cost FROM '.$this->db->prefixTable('product_supplier_cost_history').' h JOIN '.$this->db->prefixTable('items').' i ON i.id=h.product_id WHERE h.supplier_id=? GROUP BY h.product_id,i.title ORDER BY last_date DESC',[$supplierId])->getResult();}
 public function supplierHistory(int$supplierId):array{return$this->db->table('product_supplier_cost_history h')->select('h.*,i.title product_name,p.public_key,c.company_name')->join('items i','i.id=h.product_id')->join('proposals p','p.id=h.proposal_id')->join('clients c','c.id=h.client_id')->where('h.supplier_id',$supplierId)->orderBy('h.quoted_at','DESC')->get()->getResult();}
 private static function d(mixed$v):string{return bcadd((string)$v,'0',6);}}
