<?php
namespace App\Controllers\Fiscal;
use App\Controllers\Security_Controller;
use App\Models\Fiscal\Fiscal_profiles_model;
use App\Models\Fiscal\Sat_tax_regimes_model;
use App\Models\Fiscal\Sat_cfdi_uses_model;
use App\Services\Fiscal\FiscalReadinessService;

class ClientProfiles extends Security_Controller {
    private $profiles;
    public function __construct(){ parent::__construct(); $this->profiles=new Fiscal_profiles_model(); }
    private function allowed($manage=false){ if($this->login_user->is_admin) return true; $p=$this->login_user->permissions; if(!is_array($p)) $p=@unserialize((string)$p)?:[]; return (bool)get_array_value($p, $manage?'can_manage_fiscal_profiles':'can_view_fiscal_profiles'); }
    private function guard($manage=false){ if(!$this->allowed($manage)) app_redirect('forbidden'); }
    public function index($clientId=0){ $this->guard(); validate_numeric_value($clientId); return $this->template->view('fiscal/client_profiles/index',['client_id'=>$clientId,'can_manage'=>$this->allowed(true)]); }
    public function list_data($clientId=0){ $this->guard(); validate_numeric_value($clientId); $rows=[]; foreach($this->profiles->forClient((int)$clientId)->getResult() as $p){ $ready=$this->readiness($p); $rows[]=[$p->legal_name?:'-',$p->rfc?:'-',app_lang('fiscal_profile_'.$p->status),$ready['is_ready']?app_lang('ready_to_invoice'):app_lang('incomplete'),$p->is_default?app_lang('yes'):app_lang('no'),$this->allowed(true)?modal_anchor(get_uri('fiscal/client-profiles/form'),'<i data-feather="edit" class="icon-16"></i>',['data-post-id'=>$p->id,'data-post-client_id'=>$clientId,'title'=>app_lang('edit')]):'']; } echo json_encode(['data'=>$rows]); }
    public function form(){ $this->guard(true); $id=(int)$this->request->getPost('id'); $clientId=(int)$this->request->getPost('client_id'); $p=$this->profiles->get_one($id); $regimes=[''=>'-']+(new Sat_tax_regimes_model())->getActiveDropdown(['code','description']); $uses=[''=>'-']+(new Sat_cfdi_uses_model())->getActiveDropdown(['code','description']); return $this->template->view('fiscal/client_profiles/modal_form',['model_info'=>$p,'client_id'=>$clientId,'regimes'=>$regimes,'uses'=>$uses]); }
    public function save(){ $this->guard(true); $id=(int)$this->request->getPost('id'); $clientId=(int)$this->request->getPost('client_id'); $status=$this->request->getPost('status'); if(!in_array($status,['draft','incomplete','ready','inactive'],true)) $status='draft'; $data=['profile_type'=>'receiver','client_id'=>$clientId,'rfc'=>strtoupper(trim((string)$this->request->getPost('rfc'))),'legal_name'=>trim((string)$this->request->getPost('legal_name')),'tax_regime_id'=>$this->request->getPost('tax_regime_id')?:null,'fiscal_postal_code'=>trim((string)$this->request->getPost('fiscal_postal_code')),'default_cfdi_use_id'=>$this->request->getPost('default_cfdi_use_id')?:null,'tax_residency_country'=>strtoupper(trim((string)$this->request->getPost('tax_residency_country'))),'foreign_tax_registration'=>trim((string)$this->request->getPost('foreign_tax_registration')),'status'=>$status,'is_default'=>$this->request->getPost('is_default')?1:0,'updated_at'=>get_current_utc_time()]; if($status==='ready'){ $probe=(object)$data; $probe->id=$id?:null; $regime=$data['tax_regime_id']?(new Sat_tax_regimes_model())->get_one($data['tax_regime_id']):null; $use=$data['default_cfdi_use_id']?(new Sat_cfdi_uses_model())->get_one($data['default_cfdi_use_id']):null; if(!(new FiscalReadinessService())->evaluate($probe,$regime,$use)['is_ready']) $data['status']='incomplete'; } if(!$id){$data['created_by']=$this->login_user->id;$data['created_at']=get_current_utc_time();} $save=$this->profiles->ci_save($data,$id); if($save && $data['is_default']) $this->profiles->setDefault($clientId,(int)$save); echo json_encode(['success'=>(bool)$save,'id'=>$save,'message'=>$save?app_lang('record_saved'):app_lang('error_occurred')]); }
    public function set_default(){ $this->guard(true); $id=(int)$this->request->getPost('id'); $p=$this->profiles->get_one($id); echo json_encode(['success'=>$p->id ? $this->profiles->setDefault((int)$p->client_id,$id):false]); }
    public function deactivate(){ $this->guard(true); $id=(int)$this->request->getPost('id'); $data=['status'=>'inactive','is_default'=>0,'updated_at'=>get_current_utc_time()]; $ok=$this->profiles->ci_save($data,$id); echo json_encode(['success'=>(bool)$ok]); }
    private function readiness($p){ $r=$p->tax_regime_id?(new Sat_tax_regimes_model())->get_one($p->tax_regime_id):null; $u=$p->default_cfdi_use_id?(new Sat_cfdi_uses_model())->get_one($p->default_cfdi_use_id):null; return (new FiscalReadinessService())->evaluate($p,$r,$u); }
}
