<?php
namespace App\Controllers\Fiscal;
use App\Controllers\Security_Controller;
use App\Models\Fiscal\Fiscal_profiles_model;
use App\Models\Fiscal\Fiscal_series_model;
use App\Services\Fiscal\SaleFiscalReadinessService;
use App\Services\Fiscal\SaleTaxAdjustmentService;
use App\Services\Fiscal\SaleTaxPricingSimulationService;
class InvoiceReview extends Security_Controller{
 private function permissions():array{$p=$this->login_user->permissions;if(!is_array($p))$p=@unserialize((string)$p)?:[];return$p;}
 private function allowed(string$key):bool{return$this->login_user->is_admin||(bool)get_array_value($this->permissions(),$key);}
 private function guard(int$invoiceId,string$key='fiscal_sales_review'):void{$granted=$key==='fiscal_sales_review'?($this->allowed('fiscal_sales_review')||$this->allowed('fiscal_sales_pricing_review')):$this->allowed($key);if(!$granted||!$this->can_view_invoices($invoiceId))app_redirect('forbidden');}
 public function show($invoiceId=0){validate_numeric_value($invoiceId);$this->guard((int)$invoiceId);$issuerId=(int)($this->request->getPost('issuer_profile_id')?:$this->request->getGet('issuer_profile_id'));$seriesId=(int)($this->request->getPost('series_id')?:$this->request->getGet('series_id'));$receiverId=(int)($this->request->getPost('receiver_profile_id')?:$this->request->getGet('receiver_profile_id'));$review=(new SaleFiscalReadinessService())->review((int)$invoiceId,$issuerId?:null,$seriesId?:null,$receiverId?:null);$profiles=new Fiscal_profiles_model();$issuers=[];foreach($profiles->activeIssuers()->getResult()as$p)$issuers[$p->id]=$p->legal_name.' · '.$p->rfc;$invoice=db_connect()->table('invoices')->where('id',$invoiceId)->get(1)->getRow();$receivers=[];foreach($profiles->forClient((int)$invoice->client_id)->getResult()as$p)if($p->status!=='inactive')$receivers[$p->id]=$p->legal_name.' · '.$p->rfc;$series=[];if($review['issuer']['issuer_profile_id'])foreach((new Fiscal_series_model())->activeForIssuer((int)$review['issuer']['issuer_profile_id'],'ingreso')->getResult()as$s)$series[$s->id]=($s->series?:app_lang('without_series')).' · '.app_lang('next_folio').' '.max((int)$s->initial_folio,(int)$s->current_folio+1);$simulation=null;$simulationError=null;$issuer=$review['issuer']['profile']??null;$override=(string)$this->request->getPost('pricing_mode_override');$canOverride=$this->allowed('fiscal_sales_pricing_override')&&$issuer&&$issuer->allow_sale_tax_pricing_override;if(!$canOverride)$override='';if($issuer&&$review['issuer']['is_ready']){try{$simulation=(new SaleTaxPricingSimulationService())->simulate((int)$invoiceId,(int)$issuer->id,$review['receiver']['profile_id']?:(null),$review['series']['series_id']?:(null),$override?:null,(int)$this->login_user->id,true);}catch(\Throwable$e){$simulationError=$e->getMessage();}}return$this->template->view('fiscal/invoices/review',['review'=>$review,'issuers'=>$issuers,'receivers'=>$receivers,'series_options'=>$series,'simulation'=>$simulation,'simulation_error'=>$simulationError,'can_override'=>$canOverride,'can_apply'=>$this->allowed('fiscal_sales_pricing_apply')]);}
 public function apply():void{$invoiceId=(int)$this->request->getPost('invoice_id');$this->guard($invoiceId,'fiscal_sales_pricing_apply');try{$result=(new SaleTaxAdjustmentService())->confirmAndApply((int)$this->request->getPost('preparation_id'),(int)$this->login_user->id,(bool)$this->request->getPost('confirm_adjustment'));echo json_encode(['success'=>true,'message'=>app_lang('fiscal_sale_adjustment_applied'),'data'=>$result]);}catch(\Throwable$e){log_message('warning','Fiscal sale adjustment rejected: {message}',['message'=>$e->getMessage()]);echo json_encode(['success'=>false,'message'=>$e->getMessage()]);}}
}
