<?php
declare(strict_types=1);
$root = dirname(__DIR__, 2);
require $root . '/tests/bootstrap.php';
helper('general');
set_exception_handler(static function (Throwable $e) { fwrite(STDERR, $e->getMessage().PHP_EOL); exit(1); });
require APPPATH . 'Database/Migrations/2026-09-25-120000_AddProposalTemplateSelection.php';
$db = db_connect('tests');
if ($db->database !== ':memory:') throw new RuntimeException('Only an in-memory database is allowed.');
$db->query('CREATE TABLE db_proposals (id INTEGER PRIMARY KEY, content TEXT, deleted INTEGER DEFAULT 0)');
$db->query('CREATE TABLE db_proposal_templates (id INTEGER PRIMARY KEY, template TEXT, deleted INTEGER DEFAULT 0)');
$db->table('proposals')->insert(['id'=>5,'content'=>'LEGACY']);
$db->table('proposal_templates')->insert(['id'=>2,'template'=>'{PROPOSAL_ITEMS_WITH_TAXES}']);
$migration = new App\Database\Migrations\AddProposalTemplateSelection(Config\Database::forge('tests'));
$migration->up();
$migration->up();
$assert = static function ($condition,$message) { if (!$condition) throw new RuntimeException($message); echo '[PASS] '.$message.PHP_EOL; };
$row=$db->table('proposals')->where('id',5)->get()->getRow();
$assert($row->content==='LEGACY' && $row->proposal_template_id===null,'Migration is additive/idempotent and preserves historical content');
$service = new App\Services\ProposalTemplateSelectionService($db);
$service->save(5,$service->template(2)->template,2);
$row=$db->table('proposals')->where('id',5)->get()->getRow();
$assert((int)$row->proposal_template_id===2 && $row->content==='{PROPOSAL_ITEMS_WITH_TAXES}','Fresh database read preserves template ID and content together');
$db->table('proposal_templates')->where('id',2)->update(['template'=>'GLOBAL CHANGED']);
$service=new App\Services\ProposalTemplateSelectionService($db);
$service->save(5,$row->content,null);
$fresh=$db->table('proposals')->where('id',5)->get()->getRow();
$assert((int)$fresh->proposal_template_id===2 && $fresh->content===$row->content,'Snapshot and selection survive service reload and changed default/template');
echo '3 persistence checks passed.'.PHP_EOL;
