<div class="modal-body clearfix"><div class="container-fluid">
<div class="alert alert-info"><?php echo $review['warning']; ?></div>
<h5><?php echo app_lang('fiscal_review'); ?>: <?php echo app_lang('fiscal_review_status_'.$review['status']); ?></h5>
<div class="row mb15"><div class="col-md-3"><strong><?php echo app_lang('client'); ?></strong><br><?php echo $review['client_readiness']['is_ready']?app_lang('ready_to_invoice'):app_lang('incomplete'); ?></div><div class="col-md-3"><strong><?php echo app_lang('items'); ?></strong><br><?php echo $review['item_count']; ?></div><div class="col-md-3"><strong><?php echo app_lang('ready'); ?></strong><br><?php echo $review['ready_items']; ?></div><div class="col-md-3"><strong><?php echo app_lang('incomplete'); ?></strong><br><?php echo $review['incomplete_items']; ?></div></div>
<?php if($review['client_readiness']['errors']){ ?><div class="alert alert-warning"><?php echo implode('<br>',array_map('htmlspecialchars',$review['client_readiness']['errors'])); ?></div><?php } ?>
<div class="list-group"><?php foreach($review['items']as$item){$r=$item['readiness']; ?><div class="list-group-item"><strong><?php echo htmlspecialchars($item['title']); ?></strong> <span class="badge <?php echo $r['is_ready']?'bg-success':'bg-warning'; ?>"><?php echo app_lang('item_fiscal_status_'.$r['status']); ?></span><?php foreach($r['errors']as$error){ ?><div class="text-danger small"><?php echo htmlspecialchars($error); ?></div><?php } foreach($r['warnings']as$warning){ ?><div class="text-warning small"><?php echo htmlspecialchars($warning); ?></div><?php } ?></div><?php } ?></div>
<div class="mt15"><strong><?php echo app_lang('administrative_total'); ?>:</strong> <?php echo to_currency($review['administrative_total']); ?></div>
<div class="alert alert-light mt15"><?php echo app_lang('fiscal_review_no_stamp_help'); ?></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('close'); ?></button></div>
