<div class="modal-body">
<?php echo form_open(get_uri('fiscal/invoices/review/'.$review['invoice_id']),['id'=>'fiscal-sale-review-form','class'=>'general-form']); ?>
<div class="alert alert-info"><?php echo app_lang('fiscal_review_preparation_help'); ?></div><h4><?php echo app_lang('fiscal_review_status_'.$review['status']); ?></h4>
<div class="row"><div class="col-md-4"><?php echo form_dropdown('issuer_profile_id',[''=>'-']+$issuers,$review['issuer']['issuer_profile_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('fiscal_issuer'); ?></small></div><div class="col-md-4"><?php echo form_dropdown('series_id',[''=>'-']+$series_options,$review['series']['series_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('fiscal_series_single'); ?></small></div><div class="col-md-4"><?php echo form_dropdown('receiver_profile_id',[''=>'-']+$receivers,$review['receiver']['profile_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('receiver_fiscal_profile'); ?></small></div></div>
<?php if($can_override){ ?><details class="mt15"><summary><?php echo app_lang('advanced_options'); ?></summary><div class="form-group mt10"><label><?php echo app_lang('tax_pricing_override'); ?></label><?php echo form_dropdown('pricing_mode_override',[''=>app_lang('use_issuer_policy'),'tax_inclusive'=>app_lang('tax_pricing_mode_tax_inclusive'),'tax_exclusive'=>app_lang('tax_pricing_mode_tax_exclusive'),'preserve_total'=>app_lang('tax_pricing_mode_preserve_total')],$simulation['pricing_mode']??'',"class='select2 form-control'"); ?><small class="text-warning"><?php echo app_lang('tax_pricing_override_warning'); ?></small></div></details><?php } ?>
<div class="mt15"><button type="submit" class="btn btn-primary"><?php echo app_lang('refresh_review'); ?></button></div><?php echo form_close(); ?><hr>
<?php $groups=['issuer'=>app_lang('fiscal_issuer'),'receiver'=>app_lang('client'),'items'=>app_lang('items'),'series'=>app_lang('fiscal_series_single'),'sale'=>app_lang('sale')];foreach($groups as$key=>$title){?><h5><?php echo$title; ?></h5><?php foreach($review['errors'][$key]as$error){?><div class="alert alert-danger py-2"><?php echo htmlspecialchars($error); ?></div><?php }foreach($review['warnings'][$key]as$warning){?><div class="alert alert-warning py-2"><?php echo htmlspecialchars($warning); ?></div><?php }} ?>
<?php if($simulation_error){?><div class="alert alert-danger"><?php echo htmlspecialchars($simulation_error); ?></div><?php } ?>
<?php if($simulation){ ?>
<hr><h5><?php echo app_lang('price_treatment'); ?></h5><p><strong><?php echo app_lang('tax_pricing_mode_'.$simulation['pricing_mode']); ?></strong><br><?php echo app_lang('tax_pricing_mode_'.$simulation['pricing_mode'].'_help'); ?></p>
<h5><?php echo app_lang('administrative_fiscal_comparison'); ?></h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th><?php echo app_lang('concept'); ?></th><th><?php echo app_lang('current_sale'); ?></th><th><?php echo app_lang('fiscal_preparation'); ?></th></tr></thead><tbody><?php foreach([['subtotal','administrative_subtotal','estimated_fiscal_base'],['discount','administrative_discount','estimated_fiscal_discount'],['taxes','administrative_tax_total','estimated_fiscal_tax_total'],['total','administrative_total','estimated_fiscal_total'],['paid','payment_total_snapshot','payment_total_snapshot'],['balance','previous_balance','estimated_balance']]as$row){?><tr><td><?php echo app_lang($row[0]); ?></td><td><?php echo to_currency($simulation[$row[1]]); ?></td><td><?php echo to_currency($simulation[$row[2]]); ?></td></tr><?php } ?></tbody></table></div>
<div class="alert <?php echo $simulation['requires_confirmation']?'alert-warning':'alert-success'; ?>"><strong><?php echo app_lang('economic_difference'); ?>:</strong> <?php echo to_currency($simulation['difference_amount']); ?><?php if($simulation['requires_confirmation']){?><br><?php echo app_lang('sale_tax_adjustment_warning'); ?><?php } ?></div>
<?php foreach($simulation['errors']as$error){?><div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div><?php }foreach($simulation['warnings']as$warning){?><div class="alert alert-warning"><?php echo htmlspecialchars($warning); ?></div><?php } ?>
<?php if($simulation['requires_confirmation']&&$can_apply){echo form_open(get_uri('fiscal/invoices/pricing/apply'),['id'=>'apply-pricing-form','class'=>'general-form']);?><input type="hidden" name="invoice_id" value="<?php echo$review['invoice_id']; ?>"><input type="hidden" name="preparation_id" value="<?php echo$simulation['id']; ?>"><div class="form-check mb10"><?php echo form_checkbox('confirm_adjustment','1',false,"id='confirm-adjustment' class='form-check-input'"); ?><label for="confirm-adjustment"><?php echo app_lang('confirm_sale_tax_adjustment'); ?></label></div><button type="submit" class="btn btn-warning"><?php echo app_lang('apply_taxes_to_sale'); ?></button><?php echo form_close(); }} ?>
<?php if($review['series']['preview']){?><div class="alert alert-light mt15"><strong><?php echo app_lang('next_folio'); ?>:</strong> <?php echo htmlspecialchars($review['series']['preview']['series'].' '.$review['series']['preview']['folio']); ?><br><small><?php echo app_lang('preview_does_not_consume_folio'); ?></small></div><?php } ?>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('close'); ?></button></div>
<script>$(document).ready(function(){$('#fiscal-sale-review-form .select2').select2();$('#fiscal-sale-review-form').on('submit',function(e){e.preventDefault();$.post($(this).attr('action'),$(this).serialize(),function(html){$('#ajaxModalContent').html(html);});});$('#apply-pricing-form').appForm({onSuccess:function(){location.reload();}});});</script>
