<?php
declare(strict_types=1);
namespace App\Services\Fiscal\Cfdi40;
use App\Models\Fiscal\Fiscal_document_artifacts_model;
use RuntimeException;use Throwable;
final class CfdiPreXmlArtifactService{
 private $db;private string$dir;public function __construct($db=null,?string$dir=null){$this->db=$db?:db_connect();$this->dir=$dir?:WRITEPATH.'fiscal/prexml';}
 public function generate(int$documentId,int$userId,bool$authorized):array{if(!$authorized)throw new RuntimeException('No tiene permiso para generar Pre-XML.');$model=(new CfdiDraftMapper())->map($documentId);$semantic=(new CfdiSemanticValidator())->validate($model);if(!$semantic['is_valid']){$this->audit($documentId,$userId,'pre_xml_error',null,CfdiXmlBuilder::VERSION,'semantic_error');throw new RuntimeException('La validación semántica contiene errores.');}$xml=(new CfdiXmlBuilder())->build($model);$hash=hash('sha256',$xml);$artifacts=new Fiscal_document_artifacts_model();$existing=$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','builder_version'=>CfdiXmlBuilder::VERSION,'sha256'=>$hash,'superseded_at'=>null])->get(1)->getRow();if($existing)return['artifact'=>$existing,'xml'=>$xml,'semantic'=>$semantic,'xsd'=>json_decode((string)$existing->validation_payload,true)['xsd']??null,'action'=>'existing'];$xsd=(new CfdiXsdValidator())->validate($xml);$validation=['semantic'=>$semantic,'xsd'=>$xsd,'full_cfdi_validation'=>['is_valid'=>false,'reason'=>'Pendiente de certificado y sello.']];$this->ensurePrivateDir();$name=bin2hex(random_bytes(24)).'.xml';$relative='fiscal/prexml/'.$name;$target=$this->dir.DIRECTORY_SEPARATOR.$name;$tmp=$target.'.tmp.'.bin2hex(random_bytes(6));if(file_put_contents($tmp,$xml,LOCK_EX)===false||!rename($tmp,$target)){@unlink($tmp);throw new RuntimeException('No fue posible almacenar el Pre-XML de forma atómica.');}$this->db->transBegin();try{$now=get_current_utc_time();$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','superseded_at'=>null])->update(['superseded_at'=>$now]);$data=['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','storage_path'=>$relative,'sha256'=>$hash,'byte_size'=>strlen($xml),'builder_version'=>CfdiXmlBuilder::VERSION,'schema_version'=>CfdiXmlBuilder::SCHEMA_VERSION,'schema_sha256'=>$xsd['schema_sha256'],'validation_status'=>$xsd['status'],'validation_payload'=>json_encode($validation,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'created_by'=>$userId,'created_at'=>$now];$id=$artifacts->ci_save($data);$this->audit($documentId,$userId,'pre_xml_generated',$hash,CfdiXmlBuilder::VERSION,$xsd['status'],(int)$id);$this->db->transCommit();$data['id']=$id;return['artifact'=>(object)$data,'xml'=>$xml,'semantic'=>$semantic,'xsd'=>$xsd,'action'=>'created'];}catch(Throwable$e){$this->db->transRollback();@unlink($target);throw$e;}}
 public function read(int$artifactId,bool$authorized):array{if(!$authorized)throw new RuntimeException('No tiene permiso para ver Pre-XML.');$a=$this->db->table('fiscal_document_artifacts')->where(['id'=>$artifactId,'artifact_type'=>'pre_xml'])->get(1)->getRow();if(!$a)throw new RuntimeException('El artefacto no existe.');$path=$this->safePath($a->storage_path);$xml=file_get_contents($path);if($xml===false||!hash_equals($a->sha256,hash('sha256',$xml)))throw new RuntimeException('El artefacto no supera la verificación de integridad.');return['artifact'=>$a,'xml'=>$xml,'validation'=>json_decode((string)$a->validation_payload,true)];}
 private function ensurePrivateDir():void{if(!is_dir($this->dir)&&!mkdir($this->dir,0770,true)&&!is_dir($this->dir))throw new RuntimeException('No fue posible crear el almacenamiento privado.');}
 private function safePath(string$relative):string{if(!preg_match('#^fiscal/prexml/([a-f0-9]{48}\.xml)$#',$relative,$match))throw new RuntimeException('Ruta de artefacto inválida.');$base=realpath($this->dir);$path=realpath($this->dir.DIRECTORY_SEPARATOR.$match[1]);if(!$base||!$path||!str_starts_with($path,$base.DIRECTORY_SEPARATOR))throw new RuntimeException('Acceso de almacenamiento denegado.');return$path;}
 private function audit(int$documentId,int$userId,string$action,?string$hash,string$version,string$status,?int$artifactId=null):void{$doc=$this->db->table('fiscal_documents')->where('id',$documentId)->get(1)->getRow();$this->db->table('fiscal_document_audit')->insert(['fiscal_document_id'=>$documentId,'invoice_id'=>$doc->invoice_id??null,'user_id'=>$userId,'action'=>$action,'reason'=>json_encode(['artifact_id'=>$artifactId,'sha256'=>$hash,'builder_version'=>$version,'status'=>$status]),'new_hash'=>$hash,'created_at'=>get_current_utc_time()]);}
}
