<?php echo form_open(get_uri('supplier_costs/save'),['id'=>'manual-supplier-cost-form','class'=>'general-form']); ?>
<input type="hidden" name="id" value="<?php echo(int)($row->id??0); ?>"><input type="hidden" name="idempotency_key" value="<?php echo esc($token,'attr'); ?>">
<div class="modal-body"><div class="container-fluid"><div class="row">
<div class="col-md-6"><div class="form-group"><label>Producto *</label><?php echo form_dropdown('product_id',$items,$product_id,'class="form-control select2" required'); ?></div></div>
<div class="col-md-6"><div class="form-group"><label>Proveedor *</label><div class="input-group"><?php echo form_dropdown('supplier_id',$suppliers,$supplier_id,'id="manual-cost-supplier" class="form-control select2" required'); ?><?php if($can_manage_suppliers)echo modal_anchor(get_uri('suppliers/modal_form'),'<i data-feather="plus" class="icon-16"></i> Nuevo',['class'=>'btn btn-outline-secondary','data-post-quick'=>1,'title'=>'Nuevo proveedor']); ?></div></div></div>
<div class="col-md-4"><div class="form-group"><label>Costo unitario *</label><input class="form-control" type="number" min="0.000001" step="0.000001" name="unit_cost" value="<?php echo esc($row->unit_cost??'','attr'); ?>" required></div></div>
<div class="col-md-4"><div class="form-group"><label>Fecha de cotización *</label><input class="form-control" type="date" name="quoted_at" value="<?php echo esc(isset($row->quoted_at)?date('Y-m-d',strtotime($row->quoted_at)):date('Y-m-d'),'attr'); ?>" required></div></div>
<div class="col-md-4"><div class="form-group"><label>Moneda</label><input class="form-control" name="currency" maxlength="3" value="<?php echo esc($row->currency??'MXN','attr'); ?>" required></div></div>
<div class="col-md-6"><div class="form-group"><label>Cantidad (opcional)</label><input class="form-control" type="number" min="0.000001" step="0.000001" name="quantity" value="<?php echo esc($row->quantity??'','attr'); ?>"></div></div>
<div class="col-md-6"><div class="form-group"><label>Precio de venta (opcional)</label><input class="form-control" type="number" min="0" step="0.000001" name="sale_unit_price" value="<?php echo esc($row->sale_unit_price??'','attr'); ?>"></div></div>
<div class="col-md-12"><div class="form-group"><label>Notas</label><textarea class="form-control" name="notes" maxlength="2000" rows="3"><?php echo esc($row->notes??''); ?></textarea></div></div>
</div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></div><?php echo form_close(); ?>
<script>$(function(){var form=$('#manual-supplier-cost-form');form.find('.select2').select2();form.appForm({onSuccess:function(){location.reload();}});$(document).on('supplier:created.manualCost',function(e,r){if(!r||!r.id)return;var select=form.find('#manual-cost-supplier');if(!select.find('option[value="'+r.id+'"]').length)select.append(new Option(r.text||r.name||('Proveedor #'+r.id),r.id,true,true));select.val(String(r.id)).trigger('change');});});</script>